#include "css.c"
#include "vars.h"
#include "stoi.h"
#include "tools.c"
#include "criticas.c"
#include "pesquisador.c"
#include "parametros.c"
#include "../Terceiros/cadastro_terceiros.c"
#include "../Produtos/cadastro_produtos.c"
//#include "../Unidades/cadastro_unidades.c"
#include "../Compras/cadastro_compras.c"
#include "../Estoque/estoque.c"
#include "../Vendas/faturamento.c"
#include "../Listagens/relatorios.c"

