#define SERVER "localhost"
#define USER "petitto"
#define PASS "1234"
#define DATABASE "erp"
#ifdef WIN32
#define LOGGER        "/petitto/data/logger.log"
#define ICO           "/petitto/data/ico.ico"
#define MSG_PRINC     "/petitto/data/msg"
#define LOGO          "/petitto/data/logo.png"
#define INIT_IMAGE    "/petitto/data/init.jpg"
#define BACKUP        "/petitto/data/backup"
#define DESKTOP       "/petitto/data/desktop.png"
#define DESKTOP_STYLE "/petitto/data/desktop/style.css"
#define BANNER        "/petitto/data/princ_imgs/banner.png"
#define BARRA_IMG     "/petitto/data/princ_imgs/barra.png"
#define BOTAO_MENU    "/petitto/data/princ_imgs/botao_menu.png"  
#define PROD_IMG      "/petitto/data/icones_opc/produtos.png"
#define TERC_IMG      "/petitto/data/icones_opc/terceiros.png"  
#define ESTO_IMG      "/petitto/data/icones_opc/estoques.png"  
#define OPR_IMG       "/petitto/data/icones_opc/operadores.png"  
#define TRS_IMG       "/petitto/data/icones_opc/transacoes.png"  
#define SOL_IMG       "/petitto/data/icones_opc/solicitacoes.png"  
#define COT_IMG       "/petitto/data/icones_opc/cotacao.png"  
#define ORD_IMG       "/petitto/data/icones_opc/ordem_cmp.png"  
#define ENT_IMG       "/petitto/data/icones_opc/entradas.png"  
#define LMB_IMG       "/petitto/data/icones_opc/lembrete.png"  
#define UND_IMG       "/petitto/data/icones_opc/unidade.png"  
#endif
#ifdef __linux__
#define DESKTOP_STYLE "/usr/share/petitto/files/desktop/style.css"
#define DESKTOP       "/usr/share/petitto/files/desktop.png"
#define ICO           "/usr/share/petitto/files/ico.ico"
#define INIT_IMAGE    "/usr/share/petitto/files/init.jpg"
#define LOGGER        "/usr/share/petitto/files/logger"
#define BACKUP        "/usr/share/petitto/files/backup"
#define BANNER        "/usr/share/petitto/files/princ_imgs/banner.png"
#define MSG_PRINC     "/usr/share/petitto/files/msg"
#define BARRA_IMG     "/usr/share/petitto/files/princ_imgs/barra.png"
#define BOTAO_MENU    "/usr/share/petitto/files/princ_imgs/botao_menu.png"  
#define PROD_IMG      "/usr/share/petitto/files/icones_opc/produtos.png"
#define TERC_IMG      "/usr/share/petitto/files/icones_opc/terceiros.png"  
#define ESTO_IMG      "/usr/share/petitto/files/icones_opc/estoques.png"  
#define OPR_IMG       "/usr/share/petitto/files/icones_opc/operadores.png"  
#define TRS_IMG       "/usr/share/petitto/files/icones_opc/transacoes.png"  
#define SOL_IMG       "/usr/share/petitto/files/icones_opc/solicitacoes.png"  
#define COT_IMG       "/usr/share/petitto/files/icones_opc/cotacao.png"  
#define ORD_IMG       "/usr/share/petitto/files/icones_opc/ordem_cmp.png"  
#define ENT_IMG       "/usr/share/petitto/files/icones_opc/entradas.png"  
#define LMB_IMG       "/usr/share/petitto/files/icones_opc/lembrete.png"  
#define UND_IMG       "/usr/share/petitto/files/icones_opc/unidade.png"  
#endif


