const char *versions_list[] = {
	APP_VERSION_PREFIX "1.1.1.6" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1.1.5" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1.1.4" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1.1.3" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1.1.2" APP_VERSION_SUFIX APP_ENV_SO "-patch1",
	APP_VERSION_PREFIX "1.1.1.2" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1.1.1" APP_VERSION_SUFIX APP_ENV_SO "-patch-2",
	APP_VERSION_PREFIX "1.1.1.1" APP_VERSION_SUFIX APP_ENV_SO "-patch-1",
	APP_VERSION_PREFIX "1.1.1.1" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1.1" APP_VERSION_SUFIX APP_ENV_SO "-patch1",
	APP_VERSION_PREFIX "1.1.1" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.1" APP_VERSION_SUFIX APP_ENV_SO "-Patch-1",
	APP_VERSION_PREFIX "1.1" APP_VERSION_SUFIX APP_ENV_SO "-Patch-2",
	APP_VERSION_PREFIX "1.1" APP_VERSION_SUFIX APP_ENV_SO,
	APP_VERSION_PREFIX "1.0" APP_VERSION_SUFIX APP_ENV_SO,
	NULL
};

const char *compat_db_versions[] = {
	"1.1.1.5",
	NULL
};
