const char *versions_list[] = {
	"v1.1.1.4" APP_VERSION_SUFIX APP_ENV_SO,
	"v1.1.1.3" APP_VERSION_SUFIX APP_ENV_SO,
	"v1.1.1.2" APP_VERSION_SUFIX APP_ENV_SO "-patch1",
	"v1.1.1.2" APP_VERSION_SUFIX APP_ENV_SO,
	"v1.1.1.1" APP_VERSION_SUFIX APP_ENV_SO "-patch-2",
	"v1.1.1.1" APP_VERSION_SUFIX APP_ENV_SO "-patch-1",
	"v1.1.1.1" APP_VERSION_SUFIX APP_ENV_SO,
	"v1.1.1" APP_VERSION_SUFIX APP_ENV_SO "-patch1",
	"v1.1.1" APP_VERSION_SUFIX APP_ENV_SO,
	"v1.1" APP_VERSION_SUFIX APP_ENV_SO "-Patch-1",
	"v1.1" APP_VERSION_SUFIX APP_ENV_SO "-Patch-2",
	"v1.1" APP_VERSION_SUFIX APP_ENV_SO,
	"v1.0" APP_VERSION_SUFIX APP_ENV_SO,
	NULL
};


const char *compat_db_versions[] = {
	NULL
};
