#!/bin/sh

DB_CONFIG_XML=/usr/share/pedidos/files/server.xml
MIGRATE_FOLDER=data/sql_scripts/migrates

MYSQL_USER=$(sed -n -e 's/.*<usuario>\(.*\)<\/usuario>.*/\1/p' < $DB_CONFIG_XML)
MYSQL_PASSWORD=$(sed -n -e 's/.*<senha>\(.*\)<\/senha>.*/\1/p' < $DB_CONFIG_XML)
MYSQL_DATABASE=$(sed -n -e 's/.*<banco>\(.*\)<\/banco>.*/\1/p' < $DB_CONFIG_XML)


case $1 in 
	'new')
		echo "criando migrate..."
		number=1
		filename=migrate_0
		
		while [ -e $MIGRATE_FOLDER/"$filename$number.sql" ]; do
			echo "Migrate $MIGRATE_FOLDER/"$filename$number.sql" já criado"
			number=$((number+1))
		done

		echo " [!] Gerando $filename$number.sql..."
		dt_lancamento=$(echo $(date +'%Y-%m-%d'))
		template="-- migrate criado com script migrate pedidos\n\n\n"
		template="${template}update versao set versao = 'x.x', lancamento = '$dt_lancamento';\n"
		template="${template}insert into migrate values($number, 'Versao x.x', '$filename$number.sql', 'x.x', '$dt_lancamento');"
		#echo $template
		echo "$template" >> "$MIGRATE_FOLDER/$filename$number.sql"
		echo "Migrate $MIGRATE_FOLDER/"$filename$number.sql" criado com sucesso!"
		;;
	'update')
		echo "iniciando migrate..."
		for filename in `ls $MIGRATE_FOLDER/migrate*.sql | sort -g`; #data/sql_scripts/migrates/migrate*.sql; 
		do
			file=${filename##*/}
			query="select arquivo from migrate where arquivo = '$file'"
			MYSQL_PWD="$MYSQL_PASSWORD"
			saida=$(MYSQL_PWD="$MYSQL_PASSWORD" mysql -u $MYSQL_USER $MYSQL_DATABASE -e "$query" | sed -n 2p)
			#echo $saida
			
			if [ "$saida" = "" ]; then 
				echo "Arquivo $filename não foi atualizado ainda"
				query="source $PWD/$filename"
				saida=$(MYSQL_PWD="$MYSQL_PASSWORD" mysql -u $MYSQL_USER $MYSQL_DATABASE -e "$query" )
				if [ "$saida" = "" ]; then 
					echo "O migrate $filename foi atualizado"
				else
					echo $saida;
				fi
			else
				echo "$file já atualizado..."
			fi
		done
		;;
	'remove')
		if [ -z "$2" ]; then 
			echo "# Faltando argumento"
			echo "./migrate remove nome_arquivo"
			exit;

		else
			echo "removendo migrate $2 ... "
			query="select arquivo from migrate where arquivo = '$2'"
			MYSQL_PWD="$MYSQL_PASSWORD"
			saida=$(MYSQL_PWD="$MYSQL_PASSWORD" mysql -u $MYSQL_USER $MYSQL_DATABASE -e "$query" | sed -n 2p)
			if [ "$saida" = "" ]; then 
				echo "O migrate '$2' não existe"
				exit;
			fi

			query="delete from migrate where arquivo = \"$2\""
			saida=$(MYSQL_PWD="$MYSQL_PASSWORD" mysql -u $MYSQL_USER $MYSQL_DATABASE -e "$query" | tail -n +2 | sed 's/^/# /')
			if [ "$saida" = "" ]; then 
				echo "O migrate $filename foi removido"
			else
				echo $saida;
			fi
		fi
		;;
	'list')
		echo 'listando migrates atualizados'
		query="select descricao, versao, arquivo from migrate"
		saida=$(MYSQL_PWD="$MYSQL_PASSWORD" mysql -u $MYSQL_USER $MYSQL_DATABASE -e "$query" | tail -n +2 | sed 's/^/# /')
		if [ "$saida" = "" ]; then 
			echo "Não há migrates atualizados"
			exit;
		fi 
		echo "$saida"

		;;
	*)
		echo "Opção desconhecida, lista:";
		echo " - update";
		echo " - remove";
		echo " - list";
		;;
		
esac
