#include "campos/codigo_orc.c"
#include "campos/cliente_orc.c"
#include "campos/operacao_orc.c"
#include "campos/prod_orc.c"
#include "campos/qnt_orc.c"
#include "campos/preco_orc.c"
#include "campos/total_orc.c"
#include "campos/orig_preco_orc.c"
#include "campos/desconto_orc.c"
#include "campos/prod_obs_orc.c"
#include "campos/observacoes.c"
#include "campos/cond_pag.c"

#include "campos/outros/data_parc.c"
#include "campos/outros/campos_de_datas.c"
#include "campos/outros/datas_livres.c"
#include "campos/outros/sem_financeiro.c"
#include "campos/outros/banco.c"

#include "orc_p_ped.c"
#include "cancelar.c"
#include "alterar.c"
#include "excluir.c"
#include "copia.c"
#include "gerar.c"
#include "finaliza_orc.c"
#include "concluir.c"
