#include "campos/entrega_campos.h"
#include "campos/outros/data_parc.h"

#include "campos/codigo_orc.c"
#include "campos/cliente_orc.c"
#include "campos/operacao_orc.c"
#include "campos/prod_orc.c"
#include "campos/grupo.c"
#include "campos/qnt_orc.c"
#include "campos/preco_orc.c"
#include "campos/total_orc.c"
#include "campos/orig_preco_orc.c"
#include "campos/desconto_orc.c"
#include "campos/prod_obs_orc.c"
#include "campos/observacoes.c"
#include "campos/cond_pag.c"

#include "campos/entrega/transp_codigo.c"
#include "campos/entrega/transp_nome.c"
#include "campos/entrega/transp_cnpj.c"
#include "campos/entrega/transp_estado.c"
#include "campos/entrega/transp_cidade.c"
#include "campos/entrega/transp_num.c"
#include "campos/entrega/transp_ie.c"
#include "campos/entrega/transp_logradouro.c"
#include "campos/entrega/transp_bairro.c"
#include "campos/entrega/transp_cep.c"
#include "campos/entrega_campos.c"
#include "campos/outros/data_parc.c"
#include "campos/outros/campos_de_datas.c"

#include "orc_p_ped.c"
#include "cancelar.c"
#include "alterar.c"
#include "excluir.c"
#include "concluir.c"
#include "copia.c"
#include "gerar.c"
